server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: backend
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      maxLifetime: 1800000
      maximum-pool-size: 10
      auto-commit: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true