spring:
  jpa:
    hibernate:
      ddl-auto: update

allowed:
  cors:
    origins: >
      https://yonger-cathay.web.app,
      https://myapp-fujxotx5xq-de.a.run.app,
      https://yonger-cathay.firebaseapp.com