server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: backend
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      maxLifetime: 1800000
      maximum-pool-size: 10
      auto-commit: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${INSTANCE_NAME}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true