spring:
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        web: DEBUG

allowed:
  cors:
    origins: >
      http://localhost:4200,
      http://localhost:8080