spring:
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    gcp:
      sql:
        instance-connection-name: ${sm://INSTANCE_NAME}

allowed:
  cors:
    origins: ${CORS_ALLOWED_ORIGINS}


util-service:
  host: ${UTIL_SERVICE_HOST}