spring:
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    gcp:
      sql:
        instance-connection-name: ${sm://INSTANCE_NAME_DEV}

logging:
  level:
    org:
      springframework:
        web: DEBUG

allowed:
  cors:
    origins: >
      http://localhost:4200,
      http://localhost:8080,
      http://localhost:80
